# Generated by Django 5.0.1 on 2024-02-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mname', models.CharField(max_length=100)),
                ('Mdesc', models.TextField(max_length=1200)),
                ('Mprice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
