# Generated by Django 5.0.1 on 2024-02-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='Mstock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
